version: '3'

services:

  database:
    image: postgres:10.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - ./configuration/postgresql:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080

  demoservice:
      build: .
      ports:
        - 8080:8080
      environment:
        DATABASESERVER_PORT: 5432
        ENCRYPT_KEY: "spring-config-pass"
